### PR TITLE
Metrics webapp  functionalities

### PR DESCRIPTION
**Pull request by danielochuba**
# Metrics web App
### In this pull Request I implemented all the requirements to build a single page webApp.
This pull request introduces new functionality to the existing SPA web app built with React, Redux, and Tailwind CSS. It enhances the app's usability by implementing a movie detail page and enabling navigation to the details page when a movie's detail icon is clicked.

## Changes Made:

- Added a new movie detail page component (MovieDetails.js) to display comprehensive information about a selected movie.

- Created a route in the app's routing configuration (App.js) to navigate to the movie detail page when the detail icon is clicked.

- Implemented a click event handler in the movie poster to capture the click on the detail icon and trigger the navigation to the corresponding movie's detail page.

- Integrated Redux actions and reducers to manage the state related to movie data and navigation.

- Updated the API data fetching logic (api.js) to include additional movie details required for the movie detail page.

- Enhanced the styling of the movie detail page and its components using Tailwind CSS utilities.

### CODE REVIEW

**Review by 1GORDON — COMMENTED** [review]
##
## Hi @danielochuba ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [ ] Kindly ensure to add a description to your pull request listing the points you implemented in this milestone.
- [ ] I would also recommend you cross-check all the project requirements before you submit your project again.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danielochuba** [comment]
@1GORDON the changes did not reflect in my dashboard 😥😥😥😥😥😥

**Comment by danielochuba** [comment]
Screenshot 2023-07-16 033848
 
@1GORDON  Please What is happening, it is not reflecting here

**Review by 1GORDON — APPROVED** [review]
# Status: APPROVED 🟢 

Hi @danielochuba ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Project well-deployed ✔️

## Optional suggestions

- [ ] I reviewed this project based on the [pull request](https://github.com/danielochuba/Metrics-webapp/pull/2) that was accidentally merged.

- [ ] Kindly ensure all your tests are passing and are in green. 
fail-test


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
